### ISSUE TITLE
Update Wiring Diagram for Prototype

### ISSUE THREAD

**Issue by AVividLight** [Matt-and-Gib/gliChess#4]

**Comment by DualJustice** [comment]
![image](https://user-images.githubusercontent.com/80776498/177007312-6734161f-ee9f-4776-bf17-bc15698fa639.png)

**Comment by DualJustice** [comment]
The wiring diagram above does not include wiring for LEDs and is technically incomplete, but it includes all of the fundamental components.

**Comment by DualJustice** [comment]
It can also be scaled up and down given the symmetrical nature of the circuit. The decoder, in particular, is not a necessary component, but would be a nice to have in the final product.
